title: Louis Blanc
logo: image/Image_20250114140144.jpg
description: Process Automative Programmer
description: LinkedIn: https://www.linkedin.com/in/yenchi-wang/
#show_downloads: true
theme: jekyll-theme-minimal
