title: Louis Blanc
logo: image/Image_20250114140144.jpg
description: Process Automative Programmer | Applied AI Practitioner | Investment Portfolio Manager | Furry Animal Lover
#show_downloads: true
theme: jekyll-theme-minimal
